INSERT INTO tags (tag) VALUES

('Sports'),
('Football'),
('SummerGames'),
('WorldCup'),
('Championship'),
('PremierLeague'),
('Tournament2024'),
('Athletics'),
('IndoorGames'),
('OutdoorEvents'),

('TeamCompetition'),
('NationalLeague'),
('InternationalCup'),
('Olympics'),
('WinterGames'),
('FriendlyMatch'),
('QualifierRound'),
('FinalStage'),
('GroupStage'),
('KnockoutStage'),

('SemiFinals'),
('QuarterFinals'),
('RoundOf16'),
('Final'),
('PenaltyShootout'),
('ExtraTime'),
('GroupA'),
('GroupB'),
('GroupC'),
('GroupD'),

('GroupE'),
('GroupF'),
('GroupG'),
('GroupH'),
('CupFinals'),
('OpeningCeremony'),
('ClosingCeremony'),
('WorldRecord'),
('NationalRecord'),
('TieBreaker'),

('Underdog'),
('Champion'),
('RunnerUp'),
('MedalWinner'),
('AwardCeremony'),
('TeamSpirit'),
('FairPlay'),
('Sportsmanship'),
('GoldenGoal'),
('PlayOffs');