-- Insert 50 records into the teams table
INSERT INTO teams (team_name)
VALUES 
    ('Team Alpha'),
    ('Team Beta'),
    ('Team Gamma'),
    ('Team Delta'),
    ('Team Zeta'),
    ('Team Eta'),
    ('Team Theta'),
    ('Team Kappa'),
    ('Team Lambda'),
    ('Team Omega'),
    ('Team Sigma'),
    ('Team Phi'),
    ('Team Chi'),
    ('Team Psi'),
    ('Team Xi'),
    ('Team Omicron'),
    ('Team Rho'),
    ('Team Nu'),
    ('Team Mu'),
    ('Team Tau'),
    ('Team Iota'),
    ('Team Epsilon'),
    ('Team Upsilon'),
    ('Team Pi'),
    ('Team Sigma Prime'),
    ('Team Theta Prime'),
    ('Team Delta Prime'),
    ('Team Gamma Prime'),
    ('Team Alpha Prime'),
    ('Team Omega Prime'),
    ('Team Zeta Prime'),
    ('Team Lambda Prime'),
    ('Team Kappa Prime'),
    ('Team Eta Prime'),
    ('Team Psi Prime'),
    ('Team Chi Prime'),
    ('Team Omicron Prime'),
    ('Team Sigma Beta'),
    ('Team Gamma Beta'),
    ('Team Alpha Beta'),
    ('Team Theta Beta'),
    ('Team Delta Beta'),
    ('Team Kappa Beta'),
    ('Team Lambda Beta'),
    ('Team Zeta Beta'),
    ('Team Omega Beta'),
    ('Team Sigma Omega'),
    ('Team Gamma Omega'),
    ('Team Alpha Omega'),
    ('Team Theta Omega')