INSERT INTO user_detail_opinion_about_users (user_name, author, opinion) VALUES
('Alice', 'John', 'Alice is very helpful.'),
('Alice', 'Mary', 'Alice has a great sense of humor.'),
('Alice', 'Bob', 'Alice is a hard worker.'),
('Bob', 'Alice', 'Bob is very creative.'),
('Bob', 'John', 'Bob is a quick learner.'),
('Charlie', 'Alice', 'Charlie is very reliable.'),
('Charlie', 'John', 'Charlie always meets deadlines.'),
('Charlie', 'Mary', 'Charlie is detail-oriented.'),
('David', 'Alice', 'David is a great team player.'),
('David', 'Bob', 'David brings positive energy.'),
('David', 'John', 'David is always willing to help.'),
('Eva', 'Alice', 'Eva has great leadership skills.'),
('Eva', 'Mary', 'Eva is an excellent communicator.'),
('Frank', 'Bob', 'Frank is very innovative.'),
('Frank', 'Charlie', 'Frank is proactive in his work.'),
('Grace', 'David', 'Grace is very organized.'),
('Grace', 'Eva', 'Grace excels at problem-solving.'),
('Henry', 'Alice', 'Henry is very punctual.'),
('Henry', 'Mary', 'Henry has a positive attitude.'),
('Ivy', 'Alice', 'Ivy is very dependable.'),
('Ivy', 'Charlie', 'Ivy is a fast thinker.'),
('Jack', 'John', 'Jack is always improving.'),
('Jack', 'Eva', 'Jack is a good mentor.'),
('Kathy', 'Alice', 'Kathy is very resourceful.'),
('Kathy', 'Grace', 'Kathy has a strong work ethic.'),
('Leo', 'Bob', 'Leo is a critical thinker.'),
('Leo', 'Henry', 'Leo is always on time.'),
('Mia', 'John', 'Mia is very efficient.'),
('Mia', 'Alice', 'Mia is an excellent collaborator.'),
('Nina', 'Kathy', 'Nina has great ideas.'),
('Nina', 'Eva', 'Nina is highly motivated.'),
('Oscar', 'Leo', 'Oscar is very patient.'),
('Oscar', 'Mia', 'Oscar is a good listener.'),
('Paul', 'John', 'Paul is a dedicated worker.'),
('Paul', 'Alice', 'Paul is very polite.'),
('Quinn', 'David', 'Quinn is highly organized.'),
('Quinn', 'Mia', 'Quinn always stays calm under pressure.'),
('Ruth', 'Oscar', 'Ruth is very professional.'),
('Ruth', 'Nina', 'Ruth is a great analyst.'),
('Sam', 'Alice', 'Sam is very hardworking.'),
('Sam', 'Quinn', 'Sam is a quick thinker.'),
('Tina', 'Bob', 'Tina is very thorough.'),
('Tina', 'Leo', 'Tina is good at multitasking.'),
('Uma', 'Mia', 'Uma is very detail-oriented.'),
('Uma', 'Jack', 'Uma is a great problem solver.'),
('Vera', 'Eva', 'Vera has a great attitude.'),
('Vera', 'Oscar', 'Vera is very adaptable.'),
('Will', 'Paul', 'Will is very efficient.'),
('Will', 'Alice', 'Will is always looking for improvement.'),
('Xena', 'Tina', 'Xena is very creative.'),
('Xena', 'Vera', 'Xena is a strong leader.'),
('Yara', 'Uma', 'Yara is very thoughtful.'),
('Yara', 'Sam', 'Yara is a team player.'),
('Zack', 'Jack', 'Zack is very disciplined.'),
('Zack', 'Ruth', 'Zack is a great motivator.');
