INSERT INTO teams (team_name, max_amount_members, team_owner, city, is_open_recruitment) VALUES
('Alpha', 30, 'Alice', 'NewYork', true),
('Bravo', 25, 'Bob', 'LosAngeles', true),
('Charlie', 20, 'Charlie', 'Chicago', false),
('Delta', 15, 'David', 'Houston', true),
('Echo', 10, 'Eva', 'Phoenix', true),
('Foxtrot', 30, 'Frank', 'SanDiego', false),
('Golf', 28, 'Grace', 'Dallas', true),
('Hotel', 18, 'Henry', 'Austin', true),
('India', 22, 'Ivy', 'Seattle', false),
('Juliett', 30, 'Jack', 'SanJose', true),
('Kilo', 27, 'Kathy', 'SanFrancisco', true),
('Lima', 30, 'Leo', 'Boston', false),
('Mike', 25, 'Mia', 'Miami', true),
('November', 20, 'Nina', 'Atlanta', true),
('Oscar', 15, 'Oscar', 'Orlando', false),
('Papa', 30, 'Paul', 'LasVegas', true),
('Quebec', 10, 'Quinn', 'Philadelphia', true),
('Romeo', 28, 'Ruth', 'Denver', false),
('Sierra', 20, 'Sam', 'Minneapolis', true),
('Tango', 12, 'Tina', 'Sacramento', true),
('Uniform', 30, 'Uma', 'Portland', false),
('Victor', 25, 'Vera', 'Columbus', true),
('Whiskey', 15, 'Will', 'Charlotte', true),
('X-ray', 20, 'Xena', 'SanAntonio', false),
('Yankee', 28, 'Yara', 'Indianapolis', true),
('Zulu', 30, 'Zack', 'SanBernardino', true),
('Team A', 25, 'Alice', 'KansasCity', true),
('Team B', 20, 'Bob', 'Omaha', false),
('Team C', 15, 'Charlie', 'Cleveland', true),
('Team D', 10, 'David', 'Tucson', true),
('Team E', 12, 'Eva', 'VirginiaBeach', true),
('Team F', 30, 'Frank', 'Atlanta', false),
('Team G', 25, 'Grace', 'Fresno', true),
('Team H', 20, 'Henry', 'Sacramento', true),
('Team I', 18, 'Ivy', 'KansasCity', false),
('Team J', 30, 'Jack', 'Mesa', true),
('Team K', 28, 'Kathy', 'VirginiaBeach', true),
('Team L', 30, 'Leo', 'Cincinnati', false),
('Team M', 25, 'Mia', 'Pittsburgh', true),
('Team N', 20, 'Nina', 'Atlanta', true),
('Team O', 15, 'Oscar', 'Anchorage', false),
('Team P', 30, 'Paul', 'Newark', true),
('Team Q', 10, 'Quinn', 'St.Louis', true),
('Team R', 28, 'Ruth', 'Tampa', false),
('Team S', 20, 'Sam', 'Detroit', true),
('Team T', 12, 'Tina', 'LasVegas', true),
('Team U', 30, 'Uma', 'Baltimore', false),
('Team V', 25, 'Vera', 'Milwaukee', true),
('Team W', 15, 'Will', 'Albuquerque', true),
('Team X', 20, 'Xena', 'Tucson', false),
('Team Y', 28, 'Yara', 'Fresno', true),
('Team Z', 30, 'Zack', 'KansasCity', true);