
server:
  error:
    include-stacktrace: never
    include-message: always
spring:

  datasource:
#    url: jdbc:${DATABASE_DRIVER}://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/competition-tournament-service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root

#  flyway:
#    user: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    url: jdbc:${DATABASE_DRIVER}://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    schemas: ${DATABASE_NAME}
#    locations: classpath:/db/migration/structure/ddl
#    out-of-order: true
#    enabled: true

  flyway:
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/competition-tournament-service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    schemas: competition-tournament-service
    locations: classpath:/db/migration/structure/ddl
    out-of-order: true
    enabled: true

#  config:
#    import: optional:configserver:http://localhost:8888

  application:
    name: team-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9090/realms/appdevelopercompetition/protocol/openid-connect/certs"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

keycloak:
  realm: appdevelopercompetition
  domain: localhost:9090
  adminClientId: admin-cli
  adminClientSecret: qAIAkL71JnB14Fzvgsg3lQrMnwLIIKDC
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}

jwt:
  auth:
    converter:
      resource-id: authenticationClientId