ALTER TABLE competitions
  ADD COLUMN version BIGINT not NULL default 0,
  ADD COLUMN created_by VARCHAR(255),
  ADD COLUMN updated_by VARCHAR(255),
  ADD COLUMN created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;